###
GET http://localhost:3000/forms/

###
POST http://localhost:3000/insert/ 
Content-Type: application/json

{
  "firstname": "christophe",
  "lastname":"phillis",
  "email": "hristy@123@hmail",
  "message" : "bussiness",
  "addtional" : "startup idea"
}